FROM php:8.1-apache-buster

ENV APP_ENV=production
ENV APP_DEBUG=false

RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install sockets
RUN docker-php-ext-install bcmath

COPY . /var/www/html
COPY .docker/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY .env /var/www/html/.env

RUN php artisan route:cache
RUN php artisan config:clear
RUN php artisan cache:clear
RUN chmod -R 777 /var/www/html/storage
RUN chown -R www-data:www-data /var/www/html/storage
RUN a2enmod rewrite