version: "3"

services:
  mariadb:
    image: "mariadb:10.6.14-focal"
    ports:
      - "3306:3306"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_USER: secretuser
      MYSQL_PASSWORD: password
    volumes:
      - ./db-data/mariadb/:/var/lib/mysql

  user-ms:
    build:
      context: ./../user-ms
      dockerfile: ./../user-ms/dockerfile
    depends_on:
      - mariadb
      - rabbitmq
    volumes:
      - ./../user-ms:/var/www/html
    restart: always
    ports:
      - "8000:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    # entrypoint: ["php", "artisan", "migrate"]

  notification-ms:
    build:
      context: ./../notification-ms
      dockerfile: ./../notification-ms/dockerfile
    depends_on:
      - mariadb
      - rabbitmq
    volumes:
      - ./../notification-ms:/var/www/html
    restart: always
    ports:
      - "8001:80"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./db-data/rabbitmq:/var/lib/rabbitmq
      - ./db-data/rabbitmq-logs:/var/log/rabbitmq
